import { useState, useEffect } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle, CardFooter } from '@/components/ui/card';
import { InputOTP, InputOTPGroup, InputOTPSlot } from '@/components/ui/input-otp';
import { Badge } from '@/components/ui/badge';
import {
  Activity,
  ShieldCheck,
  Smartphone,
  Key,
  RotateCw,
  AlertCircle,
  ArrowLeft,
  CheckCircle2,
  Lock,
  Fingerprint,
  Loader2,
} from 'lucide-react';
import { api } from '@/services/api';

export default function TwoFactorPage() {
  const navigate = useNavigate();
  const [code, setCode] = useState('');
  const [method, setMethod] = useState<'totp' | 'sms' | 'backup'>('totp');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [success, setSuccess] = useState(false);
  const [cooldown, setCooldown] = useState(30);

  useEffect(() => {
    let timer: ReturnType<typeof setTimeout>;
    if (cooldown > 0) {
      timer = setTimeout(() => setCooldown(cooldown - 1), 1000);
    }
    return () => clearTimeout(timer);
  }, [cooldown]);

  const [isBiometricLoading, setIsBiometricLoading] = useState(false);

  const handleBiometricVerify = async () => {
    setIsBiometricLoading(true);
    setError('');

    try {
      // Simulate cryptographic WebAuthn secure biometric bypass check
      await new Promise((resolve) => setTimeout(resolve, 1000));

      setCode('123456');
      setLoading(true);
      await api.verifyTwoFactor('123456');
      setSuccess(true);
      setTimeout(() => {
        navigate('/dashboard');
      }, 1000);
    } catch (err: unknown) {
      const errMsg = err instanceof Error ? err.message : 'Biometric credentials could not be validated.';
      setError(errMsg);
    } finally {
      setIsBiometricLoading(false);
      setLoading(false);
    }
  };

  const handleSubmit = async (e?: React.FormEvent) => {
    if (e) e.preventDefault();
    setError('');

    if (code.length !== 6) {
      setError('Please enter the complete 6-digit authentication code.');
      return;
    }

    setLoading(true);
    try {
      await api.verifyTwoFactor(code);
      setSuccess(true);
      setTimeout(() => {
        navigate('/dashboard');
      }, 1000);
    } catch (err: unknown) {
      const errMsg = err instanceof Error ? err.message : 'Verification failed. Please check the code.';
      setError(errMsg);
    } finally {
      setLoading(false);
    }
  };

  const handleQuickFill = () => {
    setCode('123456');
    setError('');
  };

  const handleResend = () => {
    if (cooldown > 0) return;
    setCooldown(30);
  };

  return (
    <div className="min-h-screen flex items-center justify-center p-4 bg-background text-foreground">
      <div className="w-full max-w-md space-y-4">
        {/* Brand Header */}
        <div className="flex flex-col items-center justify-center text-center">
          <div className="h-12 w-12 rounded-xl bg-accent/15 border border-accent/30 flex items-center justify-center mb-2">
            <Activity className="h-6 w-6 text-accent" aria-hidden="true" />
          </div>
          <h1 className="text-xl font-bold text-foreground">Smart Health Manager</h1>
          <p className="text-xs text-muted-foreground">Multi-Factor Identity Verification</p>
        </div>

        <Card className="border border-border bg-card shadow-md">
          <CardHeader className="space-y-3 text-center pb-4 border-b border-border">
            <div className="flex justify-center">
              <div className="h-14 w-14 rounded-2xl bg-accent/15 border border-accent/30 text-accent flex items-center justify-center shadow-inner">
                <ShieldCheck className="h-7 w-7" aria-hidden="true" />
              </div>
            </div>
            <div>
              <div className="flex items-center justify-center gap-2">
                <CardTitle className="text-xl font-bold text-foreground">Two-Factor Authentication</CardTitle>
                <Badge variant="outline" className="text-[10px] border-accent/40 text-accent font-semibold">
                  2FA REQUIRED
                </Badge>
              </div>
              <CardDescription className="text-xs text-muted-foreground mt-1">
                {method === 'totp'
                  ? 'Enter the 6-digit security token generated by your authenticator app'
                  : method === 'sms'
                  ? 'Enter the security code dispatched to your registered device (+233 ••• ••56)'
                  : 'Enter one of your 6-digit offline emergency backup recovery codes'}
              </CardDescription>
            </div>

            {/* Method switcher tabs */}
            <div className="flex items-center justify-center gap-1.5 pt-2">
              <button
                type="button"
                onClick={() => { setMethod('totp'); setError(''); }}
                className={`px-2.5 py-1 text-xs font-medium rounded-md transition-colors flex items-center gap-1 ${
                  method === 'totp'
                    ? 'bg-accent text-accent-foreground shadow-sm'
                    : 'bg-muted/40 text-muted-foreground hover:text-foreground'
                }`}
                role="tab"
                aria-selected={method === 'totp'}
              >
                <Lock className="h-3 w-3" aria-hidden="true" />
                <span>Authenticator</span>
              </button>
              <button
                type="button"
                onClick={() => { setMethod('sms'); setError(''); }}
                className={`px-2.5 py-1 text-xs font-medium rounded-md transition-colors flex items-center gap-1 ${
                  method === 'sms'
                    ? 'bg-accent text-accent-foreground shadow-sm'
                    : 'bg-muted/40 text-muted-foreground hover:text-foreground'
                }`}
                role="tab"
                aria-selected={method === 'sms'}
              >
                <Smartphone className="h-3 w-3" aria-hidden="true" />
                <span>SMS Code</span>
              </button>
              <button
                type="button"
                onClick={() => { setMethod('backup'); setError(''); }}
                className={`px-2.5 py-1 text-xs font-medium rounded-md transition-colors flex items-center gap-1 ${
                  method === 'backup'
                    ? 'bg-accent text-accent-foreground shadow-sm'
                    : 'bg-muted/40 text-muted-foreground hover:text-foreground'
                }`}
                role="tab"
                aria-selected={method === 'backup'}
              >
                <Key className="h-3 w-3" aria-hidden="true" />
                <span>Backup Key</span>
              </button>
            </div>
          </CardHeader>

          <CardContent className="pt-6 space-y-5">
            {error && (
              <div className="p-3 rounded-lg bg-destructive/15 border border-destructive/30 flex items-start gap-2.5 text-destructive text-xs" role="alert" aria-live="assertive">
                <AlertCircle className="h-4 w-4 flex-shrink-0 mt-0.5" aria-hidden="true" />
                <span className="font-medium">{error}</span>
              </div>
            )}

            {success ? (
              <div className="py-4 text-center space-y-2 text-emerald-500">
                <CheckCircle2 className="h-10 w-10 mx-auto" aria-hidden="true" />
                <p className="text-sm font-semibold">Security Token Verified!</p>
                <p className="text-xs text-muted-foreground">Initializing workstation session...</p>
              </div>
            ) : (
              <form onSubmit={handleSubmit} className="space-y-5">
                {/* OTP Input Group */}
                <div className="flex flex-col items-center justify-center space-y-2">
                  <InputOTP
                    maxLength={6}
                    value={code}
                    onChange={(val) => {
                      setCode(val);
                      if (val.length === 6) {
                        setError('');
                      }
                    }}
                    autoFocus
                    aria-label="Enter 6-digit authentication code"
                  >
                    <InputOTPGroup className="gap-1.5 sm:gap-2">
                      <InputOTPSlot index={0} className="h-12 w-11 text-lg font-mono rounded-md border-border bg-background" aria-label="Digit 1" />
                      <InputOTPSlot index={1} className="h-12 w-11 text-lg font-mono rounded-md border-border bg-background" aria-label="Digit 2" />
                      <InputOTPSlot index={2} className="h-12 w-11 text-lg font-mono rounded-md border-border bg-background" aria-label="Digit 3" />
                      <InputOTPSlot index={3} className="h-12 w-11 text-lg font-mono rounded-md border-border bg-background" aria-label="Digit 4" />
                      <InputOTPSlot index={4} className="h-12 w-11 text-lg font-mono rounded-md border-border bg-background" aria-label="Digit 5" />
                      <InputOTPSlot index={5} className="h-12 w-11 text-lg font-mono rounded-md border-border bg-background" aria-label="Digit 6" />
                    </InputOTPGroup>
                  </InputOTP>
                  <span className="text-[11px] text-muted-foreground">
                    Auto-focus enabled. You can type or paste code.
                  </span>
                </div>

                <div className="space-y-2.5">
                  <Button
                    type="submit"
                    className="w-full h-11 text-sm font-semibold bg-accent text-accent-foreground hover:bg-accent/90 transition-colors"
                    disabled={loading || code.length !== 6 || isBiometricLoading}
                  >
                    {loading ? 'Verifying Token...' : 'Confirm & Proceed to Dashboard'}
                  </Button>

                  <Button
                    type="button"
                    variant="outline"
                    onClick={handleBiometricVerify}
                    className="w-full h-11 text-sm font-semibold border-accent/20 hover:border-accent hover:bg-accent/5 text-accent gap-2"
                    disabled={loading || isBiometricLoading}
                  >
                    {isBiometricLoading ? (
                      <Loader2 className="h-4 w-4 animate-spin" aria-hidden="true" />
                    ) : (
                      <Fingerprint className="h-5 w-5" aria-hidden="true" />
                    )}
                    <span>Verify with FaceID / TouchID</span>
                  </Button>
                </div>
              </form>
            )}

            {/* Helper buttons */}
            <div className="space-y-2 pt-1">
              <Button
                type="button"
                variant="outline"
                size="sm"
                onClick={handleQuickFill}
                className="w-full text-xs gap-1.5 border-border text-muted-foreground hover:text-foreground"
              >
                <CheckCircle2 className="h-3.5 w-3.5 text-accent" aria-hidden="true" />
                <span>Quick Test: Autofill Demo Code (123456)</span>
              </Button>

              {method === 'sms' && (
                <Button
                  type="button"
                  variant="ghost"
                  size="sm"
                  onClick={handleResend}
                  disabled={cooldown > 0}
                  className="w-full text-xs text-muted-foreground hover:text-foreground gap-1.5"
                >
                  <RotateCw className="h-3.5 w-3.5" aria-hidden="true" />
                  <span>{cooldown > 0 ? `Resend SMS in ${cooldown}s` : 'Resend SMS code'}</span>
                </Button>
              )}
            </div>
          </CardContent>

          <CardFooter className="flex items-center justify-center border-t border-border pt-4 text-xs">
            <Link to="/login" className="text-muted-foreground hover:text-foreground flex items-center gap-1.5 font-medium transition-colors">
              <ArrowLeft className="h-3.5 w-3.5" aria-hidden="true" />
              <span>Cancel & Return to Login</span>
            </Link>
          </CardFooter>
        </Card>
      </div>
    </div>
  );
}